py.install_sources(
  [
    '__init__.py',
    '_gltf.py',
    '_mesh.py',
    '_obj.py',
    '_ply.py',
    '_abaqus.py',
    '_cgns.py',
    '_3mf.py',
    '_collada.py',
    '_avs.py',
    '_dolfin.py',
    '_exodus.py',
    '_flac3d.py',
    '_fluent.py',
    '_gmsh.py',
    '_h5m.py',
    '_hdf5.py',
    '_hmf.py',
    '_las.py',
    '_lzf_fallback.py',
    '_mdpa.py',
    '_med.py',
    '_medit.py',
    '_meshb.py',
    '_nastran.py',
    '_netgen.py',
    '_off.py',
    '_pcd.py',
    '_pointcloud.py',
    '_permas.py',
    '_splat.py',
    '_stl.py',
    '_su2.py',
    '_svg.py',
    '_tecplot.py',
    '_tetgen.py',
    '_ugrid.py',
    '_vtk.py',
    '_pvd.py',
    '_pvti.py',
    '_pvtp.py',
    '_pvtr.py',
    '_pvts.py',
    '_pvtu.py',
    '_vtk_xml.py',
    '_vti.py',
    '_vtkhdf.py',
    '_vtm.py',
    '_vtp.py',
    '_vtr.py',
    '_vts.py',
    '_vtu.py',
    '_wkt.py',
    '_xdmf.py',
    '_xyz.py',
  ],
  subdir: 'polyxios/codecs',
)

py.extension_module(
  '_vtk_parse',
  '_vtk_parse.pyx',
  include_directories: inc_np,
  dependencies: py_dep,
  install: true,
  subdir: 'polyxios/codecs',
)

py.extension_module(
  '_lzf',
  '_lzf.pyx',
  dependencies: py_dep,
  install: true,
  subdir: 'polyxios/codecs',
)

py.extension_module(
  '_vtp_base64',
  '_vtp_base64.pyx',
  include_directories: inc_np,
  dependencies: py_dep,
  install: true,
  subdir: 'polyxios/codecs',
)
