from typing import Final

# Hard caps - prevent unbounded allocation from corrupt headers (meshio #1562)
MAX_SAFE_VERTICES: Final[int] = 500_000_000
MAX_SAFE_ELEMENTS: Final[int] = 2_000_000_000
MAX_SAFE_CONN: Final[int] = 8_000_000_000

# Canonical polyxios element type codes: str name - uint8 code.
# These are polyxios's own codes - do NOT use VTK integers directly.
ELEMENT_TYPES: Final[dict[str, int]] = {
    "empty_cell": 0,
    "vertex": 1,
    "poly_vertex": 2,
    "line": 3,
    "poly_line": 4,
    "triangle": 5,
    "triangle_strip": 6,
    "polygon": 7,
    "pixel": 8,
    "quad": 9,
    "tetra": 10,
    "voxel": 11,
    "hexahedron": 12,
    "wedge": 13,
    "pyramid": 14,
    "pentagonal_prism": 15,
    "hexagonal_prism": 16,
    "quadratic_edge": 17,
    "quadratic_triangle": 18,
    "quadratic_quad": 19,
    "quadratic_polygon": 20,
    "quadratic_tetra": 21,
    "quadratic_hexahedron": 22,
    "quadratic_wedge": 23,
    "quadratic_pyramid": 24,
    "biquadratic_quad": 25,
    "triquadratic_hexahedron": 26,
    "quadratic_linear_quad": 27,
    "quadratic_linear_wedge": 28,
    "biquadratic_quadratic_wedge": 29,
    "biquadratic_quadratic_hexahedron": 30,
    "biquadratic_triangle": 31,
    "cubic_line": 32,
    "convex_point_set": 33,
    "polyhedron": 34,
    "parametric_curve": 35,
    "parametric_surface": 36,
    "parametric_tri_surface": 37,
    "parametric_quad_surface": 38,
    "parametric_tetra_region": 39,
    "parametric_hex_region": 40,
    "higher_order_edge": 41,
    "higher_order_triangle": 42,
    "higher_order_quad": 43,
    "higher_order_polygon": 44,
    "higher_order_tetrahedron": 45,
    "higher_order_wedge": 46,
    "higher_order_pyramid": 47,
    "higher_order_hexahedron": 48,
    "lagrange_curve": 49,
    "lagrange_triangle": 50,
    "lagrange_quadrilateral": 51,
    "lagrange_tetrahedron": 52,
    "lagrange_hexahedron": 53,
    "lagrange_wedge": 54,
    "lagrange_pyramid": 55,
    "bezier_curve": 56,
    "bezier_triangle": 57,
}

# Reverse lookup: uint8 code - str name
ELEMENT_TYPES_INV: Final[dict[int, str]] = {v: k for k, v in ELEMENT_TYPES.items()}

# Node count per element type; -1 means variable-length (uses offsets array).
NODES_PER_ELEMENT: Final[dict[str, int]] = {
    "empty_cell": 0,
    "vertex": 1,
    "poly_vertex": -1,
    "line": 2,
    "poly_line": -1,
    "triangle": 3,
    "triangle_strip": -1,
    "polygon": -1,
    "pixel": 4,
    "quad": 4,
    "tetra": 4,
    "voxel": 8,
    "hexahedron": 8,
    "wedge": 6,
    "pyramid": 5,
    "pentagonal_prism": 10,
    "hexagonal_prism": 12,
    "quadratic_edge": 3,
    "quadratic_triangle": 6,
    "quadratic_quad": 8,
    "quadratic_polygon": -1,
    "quadratic_tetra": 10,
    "quadratic_hexahedron": 20,
    "quadratic_wedge": 15,
    "quadratic_pyramid": 13,
    "biquadratic_quad": 9,
    "triquadratic_hexahedron": 27,
    "quadratic_linear_quad": 6,
    "quadratic_linear_wedge": 12,
    "biquadratic_quadratic_wedge": 18,
    "biquadratic_quadratic_hexahedron": 24,
    "biquadratic_triangle": 7,
    "cubic_line": 4,
    "convex_point_set": -1,
    "polyhedron": -1,
    "parametric_curve": -1,
    "parametric_surface": -1,
    "parametric_tri_surface": -1,
    "parametric_quad_surface": -1,
    "parametric_tetra_region": -1,
    "parametric_hex_region": -1,
    "higher_order_edge": -1,
    "higher_order_triangle": -1,
    "higher_order_quad": -1,
    "higher_order_polygon": -1,
    "higher_order_tetrahedron": -1,
    "higher_order_wedge": -1,
    "higher_order_pyramid": -1,
    "higher_order_hexahedron": -1,
    "lagrange_curve": -1,
    "lagrange_triangle": -1,
    "lagrange_quadrilateral": -1,
    "lagrange_tetrahedron": -1,
    "lagrange_hexahedron": -1,
    "lagrange_wedge": -1,
    "lagrange_pyramid": -1,
    "bezier_curve": -1,
    "bezier_triangle": -1,
}

# VTK type integer - polyxios type name. Covers all VTK types 0–76.
# Any VTK code not in this dict - UnknownElementTypeError, never IndexError/KeyError.
VTK_TO_POLYXIOS: Final[dict[int, str]] = {
    0: "empty_cell",
    1: "vertex",
    2: "poly_vertex",
    3: "line",
    4: "poly_line",
    5: "triangle",
    6: "triangle_strip",
    7: "polygon",
    8: "pixel",
    9: "quad",
    10: "tetra",
    11: "voxel",
    12: "hexahedron",
    13: "wedge",
    14: "pyramid",
    15: "pentagonal_prism",
    16: "hexagonal_prism",
    # 17-20: undefined in VTK
    21: "quadratic_edge",
    22: "quadratic_triangle",
    23: "quadratic_quad",
    24: "quadratic_tetra",
    25: "quadratic_hexahedron",
    26: "quadratic_wedge",
    27: "quadratic_pyramid",
    28: "biquadratic_quad",
    29: "triquadratic_hexahedron",
    30: "quadratic_linear_quad",
    31: "quadratic_linear_wedge",
    32: "biquadratic_quadratic_wedge",
    33: "biquadratic_quadratic_hexahedron",
    34: "biquadratic_triangle",
    35: "cubic_line",
    36: "quadratic_polygon",
    # 37-40: undefined in VTK
    41: "convex_point_set",
    42: "polyhedron",
    # 43-50: undefined in VTK
    51: "parametric_curve",
    52: "parametric_surface",
    53: "parametric_tri_surface",
    54: "parametric_quad_surface",
    55: "parametric_tetra_region",
    56: "parametric_hex_region",
    # 57-59: undefined in VTK
    60: "higher_order_edge",
    61: "higher_order_triangle",
    62: "higher_order_quad",
    63: "higher_order_polygon",
    64: "higher_order_tetrahedron",
    65: "higher_order_wedge",
    66: "higher_order_pyramid",
    67: "higher_order_hexahedron",
    68: "lagrange_curve",
    69: "lagrange_triangle",
    70: "lagrange_quadrilateral",
    71: "lagrange_tetrahedron",
    72: "lagrange_hexahedron",
    73: "lagrange_wedge",
    74: "lagrange_pyramid",
    75: "bezier_curve",
    76: "bezier_triangle",
}

# Reverse: polyxios name - VTK integer (only for types that have a VTK mapping)
POLYXIOS_TO_VTK: Final[dict[str, int]] = {v: k for k, v in VTK_TO_POLYXIOS.items()}
